server:
  port: 8084 # 端口

spring:
  application:
    name: ms-follow # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/dinner_database?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  # Redis
  redis:
    #    port: 6379
    #    host: 127.0.0.1
    timeout: 3000
    #    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
    cluster:
      nodes:
        192.168.43.173:6371,192.168.43.173:6372,192.168.43.173:6373,192.168.43.173:6374
        ,192.168.43.173:6375,192.168.43.173:6376
      max-redirects: 5
  # Swagger
  swagger:
    base-package: com.mzh.follow
    title: 慕课美食社交食客API接口文档

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-diners-server: http://ms-diners/
    ms-feeds-server: http://ms-feeds/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'